# Generated by Django 5.1.6 on 2025-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_commande_alter_product_price_lignecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='prix',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
